### ISSUE TITLE
DGA of tufik

### ISSUE THREAD

**Issue by zulaaxx** [baderj/domain_generation_algorithms#11]
Hi,
The cmdline arg date is passed as a string to dga(), then to seed_data(), which tries to handle it as if an datetime object. Should there be "strptime" somewhere?

**Comment by baderj** [comment]
Yes, there absolutely should be. Thanks for reporting. Fixed in 43cc55445a0a463b92546b5807893d7dc32b648a.

**Comment by zulaaxx** [comment]
Thanks
