### ISSUE TITLE
Possible Bug in Orchard DGA

### ISSUE THREAD

**Issue by Manny684** [baderj/domain_generation_algorithms#12]
Hello!
I think there might be a bug in the DGA from Orchard. When you calculate the domains for a date in the past (e.g. 2022-05-09), then update the db (or rebuild it from scratch) and calculate the domains for the same date again you get different results in the second block of domains. That should not be the case, or am I missing something here?

**Comment by baderj** [comment]
Yes you are right, the implementation was wrong. It should be fixed now. The domains match the ones observed and updating the database does not change the result.

Thanks a lot for reporting the bug.
