### ISSUE TITLE
Orchard: Sorting Transactions by timestamp is ambiguous

### ISSUE THREAD

**Issue by Manny684** [baderj/domain_generation_algorithms#13]
In Orchard, when you look for the last transaction that happened before a certain date, you sort the database according to the transaction timestamps:
`    transactions = sorted(
        transactions.values(),
        key=lambda x: x['time'],
        reverse=True
    )`
In the database are multiple entries that share a timestamp, making it impossible to see which of them is the latest. I'm still trying to figure out a better sorting criterion then the timestamp but could not find one up to now. Do you have an idea how to solve this?

**Comment by baderj** [comment]
Since there are no outgoing transactions from the nemesis account, its balance is strictly increasing. I changed to sorting by balance in 54088cf221acd40379a2f0a9f5155eed4e86fbc1. Thanks for pointing out that multiple transactions could have the same timestamp.
