### ISSUE TITLE
i've made some changes to the ramnit/dga.py file. here is the patch

### ISSUE THREAD

**Issue by steodorescu** [baderj/domain_generation_algorithms#14]
please apply the patch or not at your discretion.
[ramnit-patch.diff.zip](https://github.com/baderj/domain_generation_algorithms/files/9760638/ramnit-patch.diff.zip)

**Comment by baderj** [comment]
Thanks for the patch, I have applied it in 907dbe456fb995cff2071c273d89026524b5e78d
