### ISSUE TITLE
Maybe something wrong in the md6.py

### ISSUE THREAD

**Issue by WHOLETTHEDOG-OUT** [baderj/domain_generation_algorithms#8]
I just  test the md6.py use the method in the head of the script but the script couldn't work.

Error info:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by baderj** [comment]
It looks like you are using Python 2. All scripts in this repo are for Python 3. To generate the Pykspa domains, run
```
python3 dga.py
```

from within ``pykspa/improved``.

**Comment by WHOLETTHEDOG-OUT** [comment]
ok thanks a lot! I killed the problem.
